# Generated by Django 4.0.6 on 2022-08-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TextField(max_length=100)),
            ],
        ),
    ]
