# Generated by Django 4.0.6 on 2022-08-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.IntegerField(unique=True)),
                ('vacuna_1', models.CharField(blank=True, max_length=100, null=True)),
                ('vacuna_2', models.CharField(blank=True, max_length=100, null=True)),
                ('desparasitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('castracion', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
